name: Roblox Asset Manager 3.0
on:
  repository_dispatch:
    types: [trigger_upload] # Este nome deve ser igual ao 'event_type' do Luau

jobs:
  process_asset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Python Script
        env:
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
          GITHUB_EVENT_PAYLOAD: ${{ toJson(github.event) }}
        run: python bulk_upload.py