# TITULO: GitHub Action Workflow - Versão Final Corrigida
name: Roblox Asset Automation

on:
  repository_dispatch:
    types: [trigger_upload]

jobs:
  upload_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requests
        run: pip install requests

      - name: Run Upload Script
        id: run_python
        env:
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
          # O Python deve ler estas envs para saber o que processar
          ASSET_ID: ${{ github.event.client_payload.asset_id }}
          PLAYER_NAME: ${{ github.event.client_payload.player_name }}
        run: python bulk_upload.py

      # LINHAS ADICIONADAS: Envio do Webhook com o Ficheiro
      - name: Send Webhook to Discord
        if: always() # Executa mesmo que o Python dê erro ou o Roblox dê timeout
        run: |
          # Verifica se o ficheiro assets.rbxm existe (ajuste o nome se o python gerar outro)
          if [ -f "assets.rbxm" ]; then
            curl -X POST \
              -F "file=@assets.rbxm" \
              -F "payload_json={\"content\": \"✅ **Asset Exportado com Sucesso!**\n**ID:** ${{ github.event.client_payload.asset_id }}\n**Solicitado por:** ${{ github.event.client_payload.player_name }}\"}" \
              ${{ github.event.client_payload.discord_webhook }}
          else
            echo "Erro: Ficheiro assets.rbxm não encontrado. Verifique o script Python."
            # Opcional: Enviar aviso de erro ao Discord caso o ficheiro não exista
            curl -H "Content-Type: application/json" \
                 -d "{\"content\": \"❌ Erro: O ficheiro .rbxm não foi gerado no GitHub Actions.\"}" \
                 ${{ github.event.client_payload.discord_webhook }}
          fi

      # LINHAS ADICIONADAS: Notificação para o Roblox (Faz o botão ficar verde)
      - name: Notify Roblox Messaging Service
        if: success()
        run: |
          curl -X POST "https://apis.roblox.com/messaging-service/v1/universes/${{ github.event.client_payload.experiment_id }}/topics/AssetUploadFeedback" \
            -H "x-api-key: ${{ secrets.ROBLOX_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"message\": \"{\\\"userId\\\": \\\"${{ github.event.client_payload.target_user_id }}\\\", \\\"newAssetId\\\": \\\"${{ github.event.client_payload.asset_id }}\\\"}\"
            }"
