# TITULO: GitHub Action Workflow
name: Roblox Asset Automation
on:
  repository_dispatch:
    types: [trigger_upload]

jobs:
  upload_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requests
        run: pip install requests

      - name: Run Upload Script
        env:
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
          GITHUB_EVENT_PAYLOAD: ${{ toJson(github.event) }}
        run: python bulk_upload.py
